# Generated by Django 5.2.7 on 2025-10-15 04:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Oro',
                'verbose_name_plural': 'Tipos de Oro',
            },
        ),
        migrations.CreateModel(
            name='TipoPrenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Prenda',
                'verbose_name_plural': 'Tipos de Prenda',
            },
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_chatarra', models.BooleanField(default=False)),
                ('es_recuperable', models.BooleanField(default=False)),
                ('gramos', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('existencia', models.PositiveIntegerField(default=1)),
                ('tipo_oro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prendas.tipooro')),
                ('tipo_prenda', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prendas.tipoprenda')),
            ],
            options={
                'verbose_name': 'Prenda',
                'verbose_name_plural': 'Prendas',
                'constraints': [models.CheckConstraint(condition=models.Q(('gramos__gt', 0)), name='prenda_gramos_positivos'), models.CheckConstraint(condition=models.Q(('existencia__gte', 0)), name='prenda_existencia_no_negativa')],
            },
        ),
    ]
