# Generated by Django 5.2.7 on 2025-10-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='prenda',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=100, unique=True),
        ),
    ]
