# Generated by Django 5.2.7 on 2025-10-20 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prendas', '0002_remove_prenda_descripcion_prenda_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='archivado',
            field=models.BooleanField(default=False),
        ),
    ]
