# Generated by Django 5.2.7 on 2025-10-15 04:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dominios_comunes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cuotas_pendientes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_limite', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dominios_comunes.estado')),
            ],
            options={
                'verbose_name': 'Apartado',
                'verbose_name_plural': 'Apartados',
            },
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cuotas_pendientes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('interes', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('fecha_limite', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dominios_comunes.estado')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('apartado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='apartado_credito.apartado')),
                ('credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='apartado_credito.credito')),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dominios_comunes.metodopago')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='apartado',
            constraint=models.CheckConstraint(condition=models.Q(('cuotas_pendientes__lte', models.F('cantidad_cuotas'))), name='apartado_cuotas_pendientes_validas'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('cuotas_pendientes__lte', models.F('cantidad_cuotas'))), name='credito_cuotas_pendientes_validas'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credito__isnull', False), ('apartado__isnull', True)), models.Q(('credito__isnull', True), ('apartado__isnull', False)), _connector='OR'), name='cuota_credito_xor_apartado'),
        ),
    ]
