# Generated by Django 5.2.7 on 2026-05-13 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra_venta', '0004_venta_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='iva',
        ),
    ]
